version: '2'
services:
  api:
    restart: always
    build:
      context: .
    container_name: api
    command: python -u /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      .env
    expose:
      - "9000"
    ports:
      - "9000:8000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
