# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
