# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('entries', '0003_auto_20180217_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('times', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'verbose_name': 'Recurrent',
                'verbose_name_plural': 'Recurrents',
                'ordering': ['created_date'],
            },
        ),
    ]
