# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('application_type', models.IntegerField(choices=[(0, 'Internal'), (1, 'External')], default=1)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('secret', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'OAuthApplication',
                'verbose_name_plural': 'OAuthApplications',
            },
        ),
    ]
