# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 22:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('application_type', models.IntegerField(choices=[(0, 'Internal'), (1, 'External')], default=1)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('secret', models.CharField(db_index=True, max_length=255, unique=True)),
                ('callback_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('callback_notify_extract_url', models.URLField(blank=True, null=True)),
                ('callback_notify_proposal_url', models.URLField(blank=True, null=True)),
                ('callback_notify_ticket_url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
