# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthapplication',
            options={'verbose_name': 'OAuthApplication', 'verbose_name_plural': 'OAuthApplications'},
        ),
    ]
